filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/log/nginx/*-access.log'
    fields:
      type: nginx_access
    fields_under_root: true
    scan_frequency: 5s

  - type: log
    enabled: true
    paths:
      - '/var/log/nginx/*-error.log'
    fields:
      type: nginx_error
      fields_under_root: true
      scan_frequency: 5s

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5046"]

logging.json: true
logging.metrics.enabled: false
