---
- name: 'Install'
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: 'Write config into the remote machine'
  copy:
    src: ./files/nginx.conf
    dest: /etc/nginx/sites-available/nginx.conf
    force: yes
    backup: yes

- name: clear
  file:
    path: /etc/nginx/sites-enabled
    state: absent

- name: Create directory
  file:
    path: /etc/nginx/sites-enabled
    state: directory

- name: Symlink on the app config-file
  file:
    src: /etc/nginx/sites-available/nginx.conf
    dest: /etc/nginx/sites-enabled/nginx.conf
    force: yes
    state: link

- lineinfile:
    path: /etc/hosts
    line: '10.2.0.22 logstash'

- name: Start server
  service:
    name: nginx
    enabled: yes
    state: restarted


