filebeat.inputs:
  - type: log
    paths:
      - '/var/log/app/logger.txt'

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: [logstash:5046]

logging.json: true
logging.metrics.enabled: false
