filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/log/nginx/*_access.log'
    fields:
      type: nginx_access
    fields_under_root: true
    scan_frequency: 5s

  - type: log
    enabled: true
    paths:
      - '/var/log/nginx/*_error.log'
    fields:
      type: nginx_error
      fields_under_root: true
      scan_frequency: 5s

output.logstash:
  hosts: ["127.0.0.1:5046"]

xpack.monitoring:
  enabled: true
  elasticsearch:
          hosts: ["http://127.0.0.1:9200"]
