---
- name: Install filebeat into vm-app
  hosts: app
  become: yes
  tasks:
  - name: Download filebeat from source
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.15.2- amd64.deb

  - name: Unpacking filebeat
    command: sudo dpkg -i filebeat-7.15.2-amd64.deb

  - name: Remove dafault conf filebeat.yml
    ansible.builtin.file:
      path: /etc/filebeat/filebeat.yml
      state: absent

  - name: Create custom filebeat.yml
    ansible,builtin.copy:
      src: /home/marina/ansible/files/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      force: yes
      backup: yes

  - name: Add the internal IP-address to /etc/hosts in the second machine
    lineinfile:
      dest: /etc/hosts
      lina: '10.2.0.22 logstash'
      state: present
